repo: BitBalloon/middleman-homepage
branch: cms
source_folder: "source"
collections:
  - slug: "posts"
    label: "Blog Posts"
    create: true
    folder: "blog"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h2", class: "entry-title text-center"}
      - {label: "Author", name: "author", widget: "string", tagname: "p", class: "entry-meta"}
      - {label: "Description", name: "description", widget: "string", tagname: "p"}
      - {label: "Tags", name: "tags", widget: "tags"}
      - {label: "Post Body", name: "body", widget: "markdown"}
